/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Igrac;
import java.util.LinkedList;
import komunikacija.Komunikacija;
import konstante.Operacije;
import logika.KontrolerKlijent;
import model.TabelaRezultata;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Milena Kutch
 */
public class FormaPlasman extends javax.swing.JDialog {
LinkedList<Igrac> ig = new LinkedList<>();

    public void setIg(LinkedList<Igrac> ig) {
        this.ig = ig;
    }

    public LinkedList<Igrac> getIg() {
        return ig;
    }

        
    /**
     * Creates new form FormaPlasman
     */
    public FormaPlasman(java.awt.Frame parent, boolean modal, LinkedList<Igrac>igraci) {
        super(parent, modal);
        initComponents();
        
        KontrolerKlijent.getInstance().setPlasman(this);
        tblPlasman.setModel(new TabelaRezultata());
        popuniTabelu(igraci);
        postaviMesta();
      //  pripremiTabelu(ig);
      // OsveziPlasman op = new OsveziPlasman(this);
       // op.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlasman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPlasman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPlasman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPlasman;
    // End of variables declaration//GEN-END:variables


  //  public void osvezi() {
    //    KlijentskiZahtev kz = new KlijentskiZahtev();
    //    kz.setOperacija(Operacije.UCITAJ_REZULTATE);
   //    Komunikacija.getInstance().posaljiZahtev(kz);
  //  }

    

    public void popuniTabelu(LinkedList<Igrac> ig) {
         TabelaRezultata tr = (TabelaRezultata) tblPlasman.getModel();
       tr.postaviListu(ig);
    }
    
    public void postaviMesta (){
        TabelaRezultata tr = (TabelaRezultata) tblPlasman.getModel();
        tr.postaviMesta();
    }
}
