/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Igrac;
import domen.Klub;
import domen.Partija;
import java.util.LinkedList;
import domen.Sudija;
import domen.Turnir;
import logika.KontrolerKlijent;
import model.TabelaPartije;
import sesija.Sesija;


/**
 *
 * @author Milena Kutch
 */
public class FormaGlavna extends javax.swing.JFrame {
    
private LinkedList<Igrac> IGRACI;
private LinkedList<Klub> klu;
private Turnir turnir=Sesija.getInstance().getTurnir();
private Sudija sudija=Sesija.getInstance().getUlogovani();
private int odigrano = 0;
private int aktivno = 1;
      public FormaGlavna() {
        initComponents();
        KontrolerKlijent.getInstance().setFrmglavna(this);
        KontrolerKlijent.getInstance().uzmiPrijave(turnir);
          postaviSudiju(sudija);
          postaviTurnir();
          setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         // KontrolerKlijent.getInstance().srediPanel(IGRACI);
    }
      

    public int getOdigrano() {
        return odigrano;
    }

    public void setOdigrano(int odigrano) {
        this.odigrano = odigrano;
    }

    public int getAktivno() {
        return aktivno;
    }
    public void setAktivno(int aktivno) {
        this.aktivno = aktivno;
    }

    public javax.swing.JPanel getPanelKolo() {
        return PanelKolo;
    }

    public void setPanelKolo(javax.swing.JPanel PanelKolo) {
        this.PanelKolo = PanelKolo;
    }

    public javax.swing.JButton getBtnPlasman() {
        return btnPlasman;
    }

    public void setBtnPlasman(javax.swing.JButton btnPlasman) {
        this.btnPlasman = btnPlasman;
    }

    public javax.swing.JButton getBtnSacuvaj() {
        return btnSacuvaj;
    }

    public void setBtnSacuvaj(javax.swing.JButton btnSacuvaj) {
        this.btnSacuvaj = btnSacuvaj;
    }

    public javax.swing.JButton getBtnUnesi() {
        return btnUnesi;
    }


    public void setBtnUnesi(javax.swing.JButton btnUnesi) {
        this.btnUnesi = btnUnesi;
    
    }
  

    public javax.swing.JLabel getLblAktivno() {
        return lblAktivno;
    }


    public void setLblAktivno(javax.swing.JLabel lblAktivno) {
        this.lblAktivno = lblAktivno;
    }

 
    public javax.swing.JLabel getLblOdigrano() {
        return lblOdigrano;
    }

 
    public void setLblOdigrano(javax.swing.JLabel lblOdigrano) {
        this.lblOdigrano = lblOdigrano;
    }

   
    public javax.swing.JLabel getLblSudija() {
        return lblSudija;
    }

  
    public void setLblSudija(javax.swing.JLabel lblSudija) {
        this.lblSudija = lblSudija;
    }

    public javax.swing.JLabel getLblsud() {
        return lblsud;
    }


    public void setLblsud(javax.swing.JLabel lblsud) {
        this.lblsud = lblsud;
    }

    public javax.swing.JTable getTblPartije() {
        return tblPartije;
    }

 
    public void setTblPartije(javax.swing.JTable tblPartije) {
        this.tblPartije = tblPartije;
    }

 
    public javax.swing.JTextField getTxtSudija() {
        return txtSudija;
    }


    public void setTxtSudija(javax.swing.JTextField txtSudija) {
        this.txtSudija = txtSudija;
    }

 
    public javax.swing.JTextField getTxtTurnir() {
        return txtTurnir;
    }

   
    public void setTxtTurnir(javax.swing.JTextField txtTurnir) {
        this.txtTurnir = txtTurnir;
    }
     

    public LinkedList<Klub> getKlu() {
        return klu;
    }

    public void setKlu(LinkedList<Klub> klu) {
        this.klu = klu;
    }

 

    


  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblSudija = new javax.swing.JLabel();
        lblsud = new javax.swing.JLabel();
        txtSudija = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTurnir = new javax.swing.JTextField();
        PanelKolo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblOdigrano = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAktivno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartije = new javax.swing.JTable();
        btnPlasman = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnUnesi = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsud.setText("Ulogovani sudija:");

        txtSudija.setEditable(false);

        jLabel1.setText("Aktivan turnir:");

        txtTurnir.setEditable(false);

        PanelKolo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel2.setText("Broj odigranih kola:");

        lblOdigrano.setText("jLabel3");

        jLabel4.setText("Trenutno aktivno kolo:");

        lblAktivno.setText("jLabel5");

        tblPartije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPartije);

        btnPlasman.setText("Pogledaj trenutni plasman");
        btnPlasman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlasmanActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj rezultate kola");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnUnesi.setText("Unesi rezultat odabrane partije");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKoloLayout = new javax.swing.GroupLayout(PanelKolo);
        PanelKolo.setLayout(PanelKoloLayout);
        PanelKoloLayout.setHorizontalGroup(
            PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKoloLayout.createSequentialGroup()
                .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKoloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelKoloLayout.createSequentialGroup()
                                .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelKoloLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblAktivno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelKoloLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblOdigrano, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(btnPlasman))))
                    .addGroup(PanelKoloLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnSacuvaj))
                    .addGroup(PanelKoloLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnUnesi)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelKoloLayout.setVerticalGroup(
            PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKoloLayout.createSequentialGroup()
                .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKoloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPlasman)
                        .addGap(16, 16, 16))
                    .addGroup(PanelKoloLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblOdigrano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelKoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblAktivno))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUnesi)
                .addGap(19, 19, 19)
                .addComponent(btnSacuvaj)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(lblSudija, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTurnir))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblsud)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSudija, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelKolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsud)
                    .addComponent(txtSudija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTurnir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSudija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelKolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        KontrolerKlijent.getInstance().unos();
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        KontrolerKlijent.getInstance().cuvanje(); 
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPlasmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlasmanActionPerformed

        FormaPlasman p = new FormaPlasman(this, true, IGRACI);
       
        p.setVisible(true); 
    }//GEN-LAST:event_btnPlasmanActionPerformed

   
    
    public void postaviSudiju(Sudija sudija){
        String imePrezime = sudija.getIme()+" "+sudija.getPrezime();
        getTxtSudija().setText(imePrezime);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelKolo;
    private javax.swing.JButton btnPlasman;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAktivno;
    private javax.swing.JLabel lblOdigrano;
    private javax.swing.JLabel lblSudija;
    private javax.swing.JLabel lblsud;
    private javax.swing.JTable tblPartije;
    private javax.swing.JTextField txtSudija;
    private javax.swing.JTextField txtTurnir;
    // End of variables declaration//GEN-END:variables

    public void postaviTurnir() {
        getTxtTurnir().setText(turnir.getNaziv());
        System.out.println("AKTUELNI:" +turnir.getID());
    }
    void posaljiRez(Partija izmenjena) {
        TabelaPartije tp = (TabelaPartije) getTblPartije().getModel();
        tp.izmeni(izmenjena);
    }

    public LinkedList<Igrac> getIGRACI() {
        return IGRACI;
    }

    public void setIGRACI(LinkedList<Igrac> IGRACI) {
        this.IGRACI = IGRACI;
    }

    public Turnir getTurnir() {
        return turnir;
    }

    public void setTurnir(Turnir turnir) {
        this.turnir = turnir;
    }

    public Sudija getSudija() {
        return sudija;
    }

    public void setSudija(Sudija sudija) {
        this.sudija = sudija;
    }
    }

