/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Klub;
import domen.Turnir;
import logika.KontrolerKlijent;
import sesija.Sesija;

/**
 *
 * @author Milena Kutch
 */
public class GotovTurnir extends javax.swing.JDialog {
Klub pobednicki= new Klub();
    /**
     * Creates new form GotovTurnir
     */
    public GotovTurnir(java.awt.Frame parent, boolean modal, Turnir turnir) {
        super(parent, modal);
        initComponents();
        postaviPobednicki();
        lblNaziv.setText(turnir.getNaziv());
        lblStatus.setText(turnir.getStatus());
        lblPrvo.setText(turnir.getPrvi().getIme());
        lblDrugo.setText(turnir.getDrugi().getIme());
        lblTrece.setText(turnir.getTreci().getIme());
        lblKlub.setText(pobednicki.getNaziv());
        lblKola.setText(Sesija.getInstance().getTurnir().getBrojOdigranih()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNaziv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrvo = new javax.swing.JLabel();
        lblDrugo = new javax.swing.JLabel();
        lblTrece = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblKola = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKlub = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaziv.setText("jLabel1");

        jLabel1.setText("status:");

        lblStatus.setText("jLabel2");

        jLabel2.setText("1.mesto:");

        jLabel3.setText("2.mesto:");

        jLabel4.setText("3.mesto:");

        lblPrvo.setText("jLabel5");

        lblDrugo.setText("jLabel5");

        lblTrece.setText("jLabel5");

        jLabel5.setText("broj odigranih kola:");

        lblKola.setText("jLabel6");

        jLabel6.setText("najuspesniji klub:");

        lblKlub.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrvo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTrece, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(lblDrugo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKlub)
                            .addComponent(lblKola)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStatus))
                .addGap(1, 1, 1)
                .addComponent(lblNaziv)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPrvo)
                    .addComponent(jLabel5)
                    .addComponent(lblKola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDrugo)
                    .addComponent(jLabel6)
                    .addComponent(lblKlub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTrece)
                    .addComponent(jLabel7))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
public void postaviPobednicki(){
    Turnir tu=Sesija.getInstance().getTurnir();
    if (tu.getPrvi().getKlub().getNaziv().equals(tu.getDrugi().getKlub().getNaziv())){
        pobednicki=tu.getPrvi().getKlub();
    } else if (tu.getDrugi().getKlub().getNaziv().equals(tu.getTreci().getKlub().getNaziv())){
         pobednicki=tu.getDrugi().getKlub();
    } else if (tu.getPrvi().getKlub().getNaziv().equals(tu.getTreci().getKlub().getNaziv())){
        pobednicki=tu.getPrvi().getKlub();
    } else {
        pobednicki=tu.getPrvi().getKlub();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDrugo;
    private javax.swing.JLabel lblKlub;
    private javax.swing.JLabel lblKola;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPrvo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTrece;
    // End of variables declaration//GEN-END:variables
}
