/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import komunikacija.Komunikacija;
import konstante.Operacije;
import domen.Turnir;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import logika.KontrolerKlijent;
import model.TabelaTurnira;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Milena Kutch
 */
public class PretragaTurnira extends javax.swing.JDialog {

    /**
     * Creates new form PretragaTurnira
     */
    public PretragaTurnira(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        KontrolerKlijent.getInstance().setPretragaturnira(this);
        pripremiTabelu();
        //popuniTurnire();
       // btnSve.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnnaziv = new javax.swing.JRadioButton();
        btntip = new javax.swing.JRadioButton();
        btntempo = new javax.swing.JRadioButton();
        cmbtempo = new javax.swing.JComboBox<>();
        cmbtip = new javax.swing.JComboBox<>();
        txtnaziv = new javax.swing.JTextField();
        btnSve = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurniri = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnregion = new javax.swing.JRadioButton();
        cmbregion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Odaberite i unesite kriterijum pretrage:");

        btnnaziv.setText("Naziv");
        btnnaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnazivActionPerformed(evt);
            }
        });

        btntip.setText("Tip");
        btntip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntipActionPerformed(evt);
            }
        });

        btntempo.setText("Tempo");
        btntempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntempoActionPerformed(evt);
            }
        });

        cmbtempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "redovan", "ubrzani", "brzopotezni" }));

        cmbtip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kategorni", "rejtingovan", "nerejtingovan" }));

        btnSve.setText("Prikazi sve");
        btnSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSveActionPerformed(evt);
            }
        });

        jButton1.setText("Pretraga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTurniri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTurniri);

        jButton2.setText("Izmeni turnir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnregion.setText("Region");
        btnregion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregionActionPerformed(evt);
            }
        });

        cmbregion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "evropsko", "svetsko", "balkansko", "drzavno", "opstinsko" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSve)
                                .addGap(57, 57, 57)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnregion)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbregion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btntempo)
                                            .addComponent(btntip)
                                            .addComponent(btnnaziv))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbtempo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbtip, 0, 199, Short.MAX_VALUE)
                                            .addComponent(txtnaziv))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnaziv)
                    .addComponent(txtnaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntip)
                    .addComponent(cmbtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntempo)
                    .addComponent(cmbtempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregion)
                    .addComponent(cmbregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSve)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     KontrolerKlijent.getInstance().trazenjeTurniri();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSveActionPerformed
        txtnaziv.setEditable(false);
        cmbtempo.setEnabled(false);
        cmbtip.setEnabled(false);
        btnnaziv.setSelected(false);
        btntempo.setSelected(false);
        btntip.setSelected(false);
        btnSve.setSelected(true);
         btnregion.setSelected(false);
        cmbregion.setEnabled(false);
        
    }//GEN-LAST:event_btnSveActionPerformed

    private void btntempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntempoActionPerformed
         txtnaziv.setEditable(false);
        cmbtempo.setEnabled(true);
        cmbtip.setEnabled(false);
        btnnaziv.setSelected(false);
        btntempo.setSelected(true);
        btntip.setSelected(false);
        btnSve.setSelected(false);
         btnregion.setSelected(false);
        cmbregion.setEnabled(false);
    }//GEN-LAST:event_btntempoActionPerformed

    private void btntipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntipActionPerformed
        txtnaziv.setEditable(false);
        cmbtempo.setEnabled(false);
        cmbtip.setEnabled(true);
        btnnaziv.setSelected(false);
        btntempo.setSelected(false);
        btntip.setSelected(true);
        btnSve.setSelected(false);
         btnregion.setSelected(false);
        cmbregion.setEnabled(false);
    }//GEN-LAST:event_btntipActionPerformed

    private void btnnazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnazivActionPerformed
        txtnaziv.setEditable(true);
        cmbtempo.setEnabled(false);
        cmbtip.setEnabled(false);
        btnnaziv.setSelected(true);
        btntempo.setSelected(false);
        btntip.setSelected(false);
        btnSve.setSelected(false);
         btnregion.setSelected(false);
        cmbregion.setEnabled(false);
    }//GEN-LAST:event_btnnazivActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int iz=tblTurniri.getSelectedRow();
       TabelaTurnira tt = (TabelaTurnira) tblTurniri.getModel();
        Turnir izmena = tt.getLista().get(iz);
        Sudijina fg =  (Sudijina) getParent();
        IzmenaTurnira formaIzmena = new IzmenaTurnira(fg,true,izmena);
        formaIzmena.setT(izmena);
        formaIzmena.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnregionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregionActionPerformed
          txtnaziv.setEditable(false);
        cmbtempo.setEnabled(false);
        cmbtip.setEnabled(false);
        btnnaziv.setSelected(false);
        btntempo.setSelected(false);
        btntip.setSelected(false);
        btnSve.setSelected(false);
        btnregion.setSelected(true);
        cmbregion.setEnabled(true);
    }//GEN-LAST:event_btnregionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnSve;
    private javax.swing.JRadioButton btnnaziv;
    private javax.swing.JRadioButton btnregion;
    private javax.swing.JRadioButton btntempo;
    private javax.swing.JRadioButton btntip;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cmbregion;
    private javax.swing.JComboBox<String> cmbtempo;
    private javax.swing.JComboBox<String> cmbtip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTurniri;
    private javax.swing.JTextField txtnaziv;
    // End of variables declaration//GEN-END:variables

   
    


    public void popuniTabelu(LinkedList<Turnir> turniri) {
        TabelaTurnira tt = (TabelaTurnira) tblTurniri.getModel();
        tt.postaviListu(turniri);
    }

    public void popuniTurnire() {
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.UCITAJ_TURNIRE);
            Komunikacija.getInstance().posaljiZahtev(kz);
    }

    public javax.swing.JRadioButton getBtnSve() {
        return btnSve;
    }

    public void setBtnSve(javax.swing.JRadioButton btnSve) {
        this.btnSve = btnSve;
    }

    public javax.swing.JRadioButton getBtnnaziv() {
        return btnnaziv;
    }

    public void setBtnnaziv(javax.swing.JRadioButton btnnaziv) {
        this.btnnaziv = btnnaziv;
    }

    public javax.swing.JRadioButton getBtntempo() {
        return btntempo;
    }

    public void setBtntempo(javax.swing.JRadioButton btntempo) {
        this.btntempo = btntempo;
    }

    public javax.swing.JRadioButton getBtntip() {
        return btntip;
    }

    public void setBtntip(javax.swing.JRadioButton btntip) {
        this.btntip = btntip;
    }

    public javax.swing.JComboBox<String> getCmbtempo() {
        return cmbtempo;
    }

    public void setCmbtempo(javax.swing.JComboBox<String> cmbtempo) {
        this.cmbtempo = cmbtempo;
    }

    public javax.swing.JComboBox<String> getCmbtip() {
        return cmbtip;
    }

    public void setCmbtip(javax.swing.JComboBox<String> cmbtip) {
        this.cmbtip = cmbtip;
    }

    public javax.swing.JTable getTblTurniri() {
        return tblTurniri;
    }

    public void setTblTurniri(javax.swing.JTable tblTurniri) {
        this.tblTurniri = tblTurniri;
    }

    public javax.swing.JTextField getTxtnaziv() {
        return txtnaziv;
    }

    public void setTxtnaziv(javax.swing.JTextField txtnaziv) {
        this.txtnaziv = txtnaziv;
    }

    private void pripremiTabelu() {
        TabelaTurnira tb = new TabelaTurnira();
        tblTurniri.setModel(tb);
    }

    public javax.swing.JRadioButton getBtnregion() {
        return btnregion;
    }

    public void setBtnregion(javax.swing.JRadioButton btnregion) {
        this.btnregion = btnregion;
    }

    public javax.swing.JComboBox<String> getCmbregion() {
        return cmbregion;
    }

    public void setCmbregion(javax.swing.JComboBox<String> cmbregion) {
        this.cmbregion = cmbregion;
    }
    
}
