/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import komunikacija.Komunikacija;
import konstante.Operacije;
import domen.Klub;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import logika.KontrolerKlijent;
import model.TabelaKlubova;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Milena Kutch
 */
public class PretragaKlubova extends javax.swing.JDialog {

    /**
     * Creates new form PretragaKlubova
     */
    public PretragaKlubova(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        KontrolerKlijent.getInstance().setPretragaklubova(this);
        pripremiTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnNaziv = new javax.swing.JRadioButton();
        btnGrad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtKrit = new javax.swing.JTextField();
        btnSve = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlubovi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Odaberite kriterijum za pretragu:");

        btnNaziv.setText("Naziv kluba");
        btnNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazivActionPerformed(evt);
            }
        });

        btnGrad.setText("Grad");
        btnGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradActionPerformed(evt);
            }
        });

        jLabel2.setText("Unesite vrednost kriterijuma:");

        btnSve.setText("Prikazi sve");
        btnSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSveActionPerformed(evt);
            }
        });

        tblKlubovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlubovi);

        jButton1.setText("Pretrazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSve)
                            .addComponent(btnGrad)
                            .addComponent(btnNaziv)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKrit, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(btnNaziv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrad)
                .addGap(12, 12, 12)
                .addComponent(btnSve)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     KontrolerKlijent.getInstance().trazenjeKlubovi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazivActionPerformed
        btnGrad.setSelected(false);
        btnSve.setSelected(false);
        btnNaziv.setSelected(true);
        txtKrit.setEnabled(true);
    }//GEN-LAST:event_btnNazivActionPerformed

    private void btnGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradActionPerformed
         btnGrad.setSelected(true);
        btnSve.setSelected(false);
        btnNaziv.setSelected(false);
        txtKrit.setEnabled(true);
    }//GEN-LAST:event_btnGradActionPerformed

    private void btnSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSveActionPerformed
         btnGrad.setSelected(false);
        btnSve.setSelected(true);
        btnNaziv.setSelected(false);
        txtKrit.setEnabled(false);
    }//GEN-LAST:event_btnSveActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnGrad;
    private javax.swing.JRadioButton btnNaziv;
    private javax.swing.JRadioButton btnSve;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlubovi;
    private javax.swing.JTextField txtKrit;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() {
        TabelaKlubova tk = new TabelaKlubova();
        tblKlubovi.setModel(tk);
    }

    public JTable getTblKlubovi() {
        return tblKlubovi;
    }

   

    public void popuniTabelu(LinkedList<Klub> klubovi) {
        TabelaKlubova tk = (TabelaKlubova) tblKlubovi.getModel();
        tk.postaviListu(klubovi);
    }

    public void popuniKlubove() {
              
            
           KlijentskiZahtev kz = new KlijentskiZahtev();
      kz.setOperacija(Operacije.UCITAJ_KLUBOVE);
            Komunikacija.getInstance().posaljiZahtev(kz);
       
    }

    public javax.swing.JRadioButton getBtnGrad() {
        return btnGrad;
    }

    public void setBtnGrad(javax.swing.JRadioButton btnGrad) {
        this.btnGrad = btnGrad;
    }

    public javax.swing.JRadioButton getBtnNaziv() {
        return btnNaziv;
    }

    public void setBtnNaziv(javax.swing.JRadioButton btnNaziv) {
        this.btnNaziv = btnNaziv;
    }

    public javax.swing.JRadioButton getBtnSve() {
        return btnSve;
    }

    public void setBtnSve(javax.swing.JRadioButton btnSve) {
        this.btnSve = btnSve;
    }

    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public javax.swing.ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public javax.swing.JTextField getTxtKrit() {
        return txtKrit;
    }

    public void setTxtKrit(javax.swing.JTextField txtKrit) {
        this.txtKrit = txtKrit;
    }

 
}
