/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import komunikacija.Komunikacija;
import konstante.Operacije;
import domen.Igrac;
import domen.Klub;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import logika.KontrolerKlijent;
import model.TabelaIgraca;
import sesija.Sesija;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Milena Kutch
 */
public class PretragaIgraca extends javax.swing.JDialog {
//private LinkedList<Igrac> cuvamListu;
    /**
     * Creates new form PretragaIgraca
     */
    public PretragaIgraca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ucitajKlubove();
        pripremiTabelu();
        KontrolerKlijent.getInstance().setPretragaigraca(this);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnklub = new javax.swing.JRadioButton();
        btnkat = new javax.swing.JRadioButton();
        cmbKlub = new javax.swing.JComboBox();
        cmbkat = new javax.swing.JComboBox<>();
        btnSve = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnime = new javax.swing.JRadioButton();
        txtime = new javax.swing.JTextField();
        btnprezime = new javax.swing.JRadioButton();
        txtprezime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Odaberite kriterijum za pretragu i unesite/odaberite vrednost:");

        btnklub.setText("klub");
        btnklub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnklubActionPerformed(evt);
            }
        });

        btnkat.setText("kategorija");
        btnkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkatActionPerformed(evt);
            }
        });

        cmbKlub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IV", "III", "II", "I", "MK", "FM", "IM", "VM" }));
        cmbkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatActionPerformed(evt);
            }
        });

        btnSve.setText("prikazi sve");
        btnSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSveActionPerformed(evt);
            }
        });

        jButton1.setText("Pretraga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnime.setText("ime");
        btnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimeActionPerformed(evt);
            }
        });

        btnprezime.setText("prezime");
        btnprezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprezimeActionPerformed(evt);
            }
        });

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIgraci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSve)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnprezime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtprezime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnkat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbkat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnklub)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKlub, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnklub)
                    .addComponent(cmbKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkat)
                    .addComponent(cmbkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnime)
                    .addComponent(txtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprezime))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSve)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   KontrolerKlijent.getInstance().trazenjeIgraci();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSveActionPerformed
        
        txtime.setEnabled(false);
        txtprezime.setEnabled(false);
        cmbkat.setEnabled(false);
        cmbKlub.setEnabled(false);
        btnSve.setSelected(true);
        btnime.setSelected(false);
        btnprezime.setSelected(false);
        btnkat.setSelected(false);
        btnklub.setSelected(false);

    }//GEN-LAST:event_btnSveActionPerformed

    private void cmbkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatActionPerformed

    private void btnprezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprezimeActionPerformed
        txtime.setEnabled(false);
        txtprezime.setEnabled(true);
        cmbkat.setEnabled(false);
        cmbKlub.setEnabled(false);
        btnSve.setSelected(false);
        btnime.setSelected(false);
        btnprezime.setSelected(true);
        btnkat.setSelected(false);
        btnklub.setSelected(false);
    }//GEN-LAST:event_btnprezimeActionPerformed

    private void btnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimeActionPerformed
        txtime.setEnabled(true);
        txtprezime.setEnabled(false);
        cmbkat.setEnabled(false);
        cmbKlub.setEnabled(false);
        btnSve.setSelected(false);
        btnime.setSelected(true);
        btnprezime.setSelected(false);
        btnkat.setSelected(false);
        btnklub.setSelected(false);
    }//GEN-LAST:event_btnimeActionPerformed

    private void btnkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkatActionPerformed
        txtime.setEnabled(false);
        txtprezime.setEnabled(false);
        cmbkat.setEnabled(true);
        cmbKlub.setEnabled(false);
        btnSve.setSelected(false);
        btnime.setSelected(false);
        btnprezime.setSelected(false);
        btnkat.setSelected(true);
        btnklub.setSelected(false);
    }//GEN-LAST:event_btnkatActionPerformed

    private void btnklubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnklubActionPerformed
       txtime.setEnabled(false);
        txtprezime.setEnabled(false);
        cmbkat.setEnabled(false);
        cmbKlub.setEnabled(true);
        btnSve.setSelected(false);
        btnime.setSelected(false);
        btnprezime.setSelected(false);
        btnkat.setSelected(false);
        btnklub.setSelected(true);
    }//GEN-LAST:event_btnklubActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnSve;
    private javax.swing.JRadioButton btnime;
    private javax.swing.JRadioButton btnkat;
    private javax.swing.JRadioButton btnklub;
    private javax.swing.JRadioButton btnprezime;
    private javax.swing.JComboBox cmbKlub;
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIgraci;
    private javax.swing.JTextField txtime;
    private javax.swing.JTextField txtprezime;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() {
        TabelaIgraca ti = new TabelaIgraca();
        tblIgraci.setModel(ti);
        ti.postaviListu(Sesija.getInstance().getIgraciLista());
    }


    public void popuniTabelu(LinkedList<Igrac> igraci) {
        TabelaIgraca ti = (TabelaIgraca) tblIgraci.getModel();
        ti.postaviListu(igraci);
    }

   

    private void ucitajKlubove() {
        
            KlijentskiZahtev kz = new KlijentskiZahtev();
      kz.setOperacija(Operacije.UZMI_KLUBOVE);
            Komunikacija.getInstance().posaljiZahtev(kz);
    }

    public void popuniKlubove(LinkedList<Klub> klulil) {
         cmbKlub.removeAllItems();
        for (Klub klub : klulil) {
            cmbKlub.addItem(klub);
        }
    }
 public void popuniIgrace() {
          
      KlijentskiZahtev kz = new KlijentskiZahtev();
      kz.setOperacija(Operacije.UCITAJ_IGRACE);
      Komunikacija.getInstance().posaljiZahtev(kz);
        }
   
    public javax.swing.JTextField getTxtprezime() {
        return txtprezime;
    }

    public void setTxtprezime(javax.swing.JTextField txtprezime) {
        this.txtprezime = txtprezime;
    }

    public javax.swing.JTextField getTxtime() {
        return txtime;
    }

    public void setTxtime(javax.swing.JTextField txtime) {
        this.txtime = txtime;
    }

    public javax.swing.JTable getTblIgraci() {
        return tblIgraci;
    }

    public void setTblIgraci(javax.swing.JTable tblIgraci) {
        this.tblIgraci = tblIgraci;
    }

    public javax.swing.JComboBox<String> getCmbkat() {
        return cmbkat;
    }

    public void setCmbkat(javax.swing.JComboBox<String> cmbkat) {
        this.cmbkat = cmbkat;
    }

    public javax.swing.JComboBox getCmbKlub() {
        return cmbKlub;
    }

    public void setCmbKlub(javax.swing.JComboBox cmbKlub) {
        this.cmbKlub = cmbKlub;
    }

    public javax.swing.JRadioButton getBtnprezime() {
        return btnprezime;
    }

    public void setBtnprezime(javax.swing.JRadioButton btnprezime) {
        this.btnprezime = btnprezime;
    }

    public javax.swing.JRadioButton getBtnklub() {
        return btnklub;
    }

    public void setBtnklub(javax.swing.JRadioButton btnklub) {
        this.btnklub = btnklub;
    }

    public javax.swing.JRadioButton getBtnkat() {
        return btnkat;
    }

    public void setBtnkat(javax.swing.JRadioButton btnkat) {
        this.btnkat = btnkat;
    }

    public javax.swing.JRadioButton getBtnime() {
        return btnime;
    }

    public void setBtnime(javax.swing.JRadioButton btnime) {
        this.btnime = btnime;
    }

    public javax.swing.JRadioButton getBtnSve() {
        return btnSve;
    }

    public void setBtnSve(javax.swing.JRadioButton btnSve) {
        this.btnSve = btnSve;
    }
    }
 

