/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Partija;
import java.awt.Frame;
import javax.swing.JOptionPane;
import logika.KontrolerKlijent;
import sesija.Sesija;

/**
 *
 * @author Milena Kutch
 */
public class UnosRezultataPartije extends javax.swing.JDialog {
private Partija izmenjena;
    /**
     * Creates new form UnosRezultataPartije
     */
    public UnosRezultataPartije(Frame parent, boolean modal, Partija zaIzmenu) {
        super(parent, modal);
        initComponents();
        KontrolerKlijent.getInstance().setUnosrez(this);
        lblSudija.setText(Sesija.getInstance().getUlogovani().getIme());
        lblBeli.setText(zaIzmenu.getBeli().getIme());
        lblCrni.setText(zaIzmenu.getCrni().getIme());
        izmenjena = zaIzmenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSudija = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbB = new javax.swing.JComboBox();
        lblBeli = new javax.swing.JLabel();
        lblCrni = new javax.swing.JLabel();
        cmbC = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ovlasceni sudija:");

        lblSudija.setText("jLabel2");

        jLabel2.setText("Unesite rezultat:");

        cmbB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "0.5", "1" }));

        lblBeli.setText("jLabel3");

        lblCrni.setText("jLabel3");

        cmbC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "0.5", "1" }));

        jButton1.setText("Azuriraj partiju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(lblCrni)
                                .addGap(18, 18, 18)
                                .addComponent(cmbC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSudija, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSudija))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeli)
                    .addComponent(lblCrni)
                    .addComponent(cmbC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         double pb = Double.parseDouble((String) cmbB.getSelectedItem());
         double pc = Double.parseDouble((String) cmbC.getSelectedItem());
        if ((pb==pc) && (pb!=0.5 || pc!=0.5)){
            JOptionPane.showMessageDialog(this, "nepravilno unesen rezultat" );
            return;
        }
        if ((pb==1 && pc==0.5) || (pb==0 && pc==0.5)){
             JOptionPane.showMessageDialog(this, "nepravilno unesen rezultat" );
            return;
        }
         if ((pc==1 && pb==0.5) || (pc==0 && pb==0.5)){
             JOptionPane.showMessageDialog(this, "nepravilno unesen rezultat" );
            return;
        }
         izmenjena.setBodovibeli(pb);
         izmenjena.setBodovicrni(pc);
         FormaGlavna fg = (FormaGlavna) getParent();
         fg.posaljiRez(izmenjena);
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbB;
    private javax.swing.JComboBox cmbC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBeli;
    private javax.swing.JLabel lblCrni;
    private javax.swing.JLabel lblSudija;
    // End of variables declaration//GEN-END:variables

    public Partija getIzmenjena() {
        return izmenjena;
    }

    public void setIzmenjena(Partija izmenjena) {
        this.izmenjena = izmenjena;
    }

    public javax.swing.JComboBox getCmbB() {
        return cmbB;
    }

    public void setCmbB(javax.swing.JComboBox cmbB) {
        this.cmbB = cmbB;
    }

    public javax.swing.JComboBox getCmbC() {
        return cmbC;
    }

    public void setCmbC(javax.swing.JComboBox cmbC) {
        this.cmbC = cmbC;
    }
}
